# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61b8095400955c5b6eeb245d64923dbd800b4453d80706bc9440624780e77207c85d63ca48b42fbd16d0dd7d94054aec9294f6bfd85479c07ec0443f5617021b

test:
  secret_key_base: e8f709c104bd5afc9fff1ee5d2319f5fe85e186ad351faea6416c662c7e1bd57d1e6aad7f6f3c72efa2257ba4c03cba394ac1934a257c63163bed19c27b68a4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
